version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Setup Enviroment
          command: |
            echo 'export IMAGE_NAME=python-cicd-workshop' >> $BASH_ENV 
            virtualenv myapp
            . myapp/bin/activate

      - run:
          name: Install Python Dependencies
          command: |
            . myapp/bin/activate
            make install

      - save_cache:
          paths:
            - ./myapp
          key: v1-dependencies-{{ checksum "requirements.txt" }}
            
      - run:
          name: Lint the App
          command: |
            . myapp/bin/activate            
            make lint

      - run:
          name: Run tests
          command: |
            . myapp/bin/activate
            python test_my_app.py

  build-and-push-docker-image:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Build and Push Docker Image
          command: |
            . myapp/bin/activate
            pyinstaller -F my_app.py
            docker build -t $DOCKER_LOGIN/$IMAGE_NAME .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $DOCKER_LOGIN/$IMAGE_NAME


workflows:
  main:
    jobs:
      - build-and-test
      - build-and-push-docker-image:
          requires:
            - build-and-test
          filters:
            branches:
              only: master